/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.administracao.telas;

import org.example.estadioArbitragem.Arbitro;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.example.administracao.AdministraUsuario;
import org.example.administracao.Administrador;
import org.example.administracao.Operador;
import org.example.administracao.Organizador;
import org.example.administracao.Papel;
import org.example.administracao.PersistenciaUsuario;
import org.example.administracao.Usuario;
import org.example.administracao.UsuarioLogado;
import org.example.administracao.excecoes.CamposEmBrancoException;
import org.example.administracao.excecoes.SenhaInsuficienteException;

/**
 *
 * @author arkham
 */
public class GestaoUsuarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestaoUsuarios.class.getName());
    
    UsuarioLogado sessao;
    PersistenciaUsuario persistenciaUsuario;

    /**
     * Creates new form GestaoUsuarios
     * @param sessao instancia de UsuarioLogado para verificar caracteristicas do usuario atual
     * @param persistenciaUsuario instancia de PersistenciaUsuario para armazenar no arquivo a depender do ambiente
     */ 
    public GestaoUsuarios(UsuarioLogado sessao, PersistenciaUsuario persistenciaUsuario) {
        this.sessao = sessao;
        this.persistenciaUsuario = persistenciaUsuario;
        initComponents();
        
        desabilitaInputPesquisa();
        caixaExperiencia.setVisible(false);
        textoExperiencia.setVisible(false);
    }
    
    private void preencheTabela(List<Usuario> listaUsuario) {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tabelaUsuarios.getModel();
        
        modelo.setRowCount(0);
        modelo.setColumnIdentifiers(new Object[]{"Nome", "ID", "Função", "País"});
        
        
        for (Usuario e : listaUsuario) {
            modelo.addRow(new Object[] {
                e.getNome(),
                e.getIdentificacao(),
                e.getPapel(),
                e.getPais()
            });
        }
    }
    
    private void desabilitaInputPesquisa() {
        checkInputNome.setEnabled(false);
        checkInputEmail.setEnabled(false);
        caixaCheckFuncao.setEnabled(false);
        checkInputID.setEnabled(false);
        checkInputPais.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoUsuario = new javax.swing.ButtonGroup();
        grupoStatusUsuario = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        painelCadastraUsuario = new javax.swing.JPanel();
        textoNome = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        textoEmail = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        textoSenha = new javax.swing.JLabel();
        textoTipoUsuario = new javax.swing.JLabel();
        botaoSalvarUsuario = new javax.swing.JButton();
        inputSenha = new javax.swing.JPasswordField();
        textoPais = new javax.swing.JLabel();
        inputPais = new javax.swing.JTextField();
        textoStatus = new javax.swing.JLabel();
        botaoFechar = new javax.swing.JButton();
        caixaTipoUsuario = new javax.swing.JComboBox<>();
        caixaStatusUsuario = new javax.swing.JComboBox<>();
        textoExperiencia = new javax.swing.JLabel();
        caixaExperiencia = new javax.swing.JComboBox<>();
        painelPesquisaUsuario = new javax.swing.JPanel();
        checkNome = new javax.swing.JCheckBox();
        checkInputNome = new javax.swing.JTextField();
        checkFuncao = new javax.swing.JCheckBox();
        checkIdentificacao = new javax.swing.JCheckBox();
        checkInputID = new javax.swing.JTextField();
        checkEmail = new javax.swing.JCheckBox();
        checkInputEmail = new javax.swing.JTextField();
        checkPais = new javax.swing.JCheckBox();
        checkInputPais = new javax.swing.JTextField();
        botaoPesquisa = new javax.swing.JButton();
        botaoLista = new javax.swing.JButton();
        scrollUsuarios = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();
        caixaCheckFuncao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoNome.setText("Nome completo: ");

        textoEmail.setText("E-mail:");

        textoSenha.setText("Senha:");

        textoTipoUsuario.setText("Tipo de usuário:");

        botaoSalvarUsuario.setText("Salvar");
        botaoSalvarUsuario.addActionListener(this::botaoSalvarUsuarioActionPerformed);

        textoPais.setText("País:");

        textoStatus.setText("Status do usuário:");

        botaoFechar.setText("Fechar");
        botaoFechar.addActionListener(this::botaoFecharActionPerformed);

        caixaTipoUsuario.addItem(new Administrador());
        caixaTipoUsuario.addItem(new Organizador());
        caixaTipoUsuario.addItem(new Operador());
        caixaTipoUsuario.addItem(new Arbitro());
        caixaTipoUsuario.addActionListener(this::caixaTipoUsuarioActionPerformed);

        caixaStatusUsuario.addItem(Usuario.StatusUsuario.ATIVO);
        caixaStatusUsuario.addItem(Usuario.StatusUsuario.AFASTADO);
        caixaStatusUsuario.addItem(Usuario.StatusUsuario.DESLIGADO);
        caixaStatusUsuario.addActionListener(this::caixaStatusUsuarioActionPerformed);

        textoExperiencia.setText("Experiência:");

        caixaExperiencia.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }));
        caixaExperiencia.addActionListener(this::caixaExperienciaActionPerformed);

        javax.swing.GroupLayout painelCadastraUsuarioLayout = new javax.swing.GroupLayout(painelCadastraUsuario);
        painelCadastraUsuario.setLayout(painelCadastraUsuarioLayout);
        painelCadastraUsuarioLayout.setHorizontalGroup(
            painelCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastraUsuarioLayout.createSequentialGroup()
                .addGroup(painelCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastraUsuarioLayout.createSequentialGroup()
                        .addGroup(painelCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCadastraUsuarioLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(textoTipoUsuario))
                            .addGroup(painelCadastraUsuarioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(painelCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoStatus)
                                    .addComponent(botaoSalvarUsuario)
                                    .addComponent(textoExperiencia))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNome, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(inputEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(inputPais, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaStatusUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caixaExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelCadastraUsuarioLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(botaoFechar))
                    .addGroup(painelCadastraUsuarioLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textoEmail))
                    .addGroup(painelCadastraUsuarioLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(textoNome))
                    .addGroup(painelCadastraUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textoSenha))
                    .addGroup(painelCadastraUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textoPais)))
                .addContainerGap(295, Short.MAX_VALUE))
        );

        painelCadastraUsuarioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {inputEmail, inputNome, inputPais, inputSenha});

        painelCadastraUsuarioLayout.setVerticalGroup(
            painelCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastraUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNome)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoEmail))
                .addGap(18, 18, 18)
                .addGroup(painelCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoPais)
                    .addComponent(inputPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoSenha)
                    .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTipoUsuario)
                    .addComponent(caixaTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoStatus)
                    .addComponent(caixaStatusUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoExperiencia)
                    .addComponent(caixaExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(painelCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvarUsuario)
                    .addComponent(botaoFechar))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        painelCadastraUsuarioLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {inputEmail, inputNome, inputPais, inputSenha});

        jTabbedPane1.addTab("Criar usuário", painelCadastraUsuario);

        checkNome.setText("Nome:  ");
        checkNome.addActionListener(this::checkNomeActionPerformed);

        checkInputNome.addActionListener(this::checkInputNomeActionPerformed);

        checkFuncao.setText("Função:  ");
        checkFuncao.addActionListener(this::checkFuncaoActionPerformed);

        checkIdentificacao.setText("Identificação");
        checkIdentificacao.addActionListener(this::checkIdentificacaoActionPerformed);

        checkEmail.setText("E-mail");
        checkEmail.addActionListener(this::checkEmailActionPerformed);

        checkPais.setText("País");
        checkPais.addActionListener(this::checkPaisActionPerformed);

        botaoPesquisa.setText("Pesquisar...");
        botaoPesquisa.addActionListener(this::botaoPesquisaActionPerformed);

        botaoLista.setText("Listar todos os usuários...");
        botaoLista.addActionListener(this::botaoListaActionPerformed);

        scrollUsuarios.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrollUsuariosMouseClicked(evt);
            }
        });

        tabelaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaUsuariosMouseClicked(evt);
            }
        });
        scrollUsuarios.setViewportView(tabelaUsuarios);

        caixaCheckFuncao.addItem(null);
        caixaCheckFuncao.addItem(new Administrador());
        caixaCheckFuncao.addItem(new Organizador());
        caixaCheckFuncao.addItem(new Operador());
        caixaCheckFuncao.addItem(new Arbitro());

        javax.swing.GroupLayout painelPesquisaUsuarioLayout = new javax.swing.GroupLayout(painelPesquisaUsuario);
        painelPesquisaUsuario.setLayout(painelPesquisaUsuarioLayout);
        painelPesquisaUsuarioLayout.setHorizontalGroup(
            painelPesquisaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPesquisaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                    .addGroup(painelPesquisaUsuarioLayout.createSequentialGroup()
                        .addGroup(painelPesquisaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkNome)
                            .addComponent(checkFuncao)
                            .addComponent(checkIdentificacao)
                            .addComponent(checkEmail)
                            .addComponent(checkPais)
                            .addComponent(botaoPesquisa))
                        .addGap(21, 21, 21)
                        .addGroup(painelPesquisaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkInputNome, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(checkInputID, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(checkInputEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(checkInputPais, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(botaoLista)
                            .addComponent(caixaCheckFuncao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        painelPesquisaUsuarioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {checkInputEmail, checkInputID, checkInputNome, checkInputPais});

        painelPesquisaUsuarioLayout.setVerticalGroup(
            painelPesquisaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPesquisaUsuarioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(painelPesquisaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkNome)
                    .addComponent(checkInputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelPesquisaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkFuncao)
                    .addComponent(caixaCheckFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(painelPesquisaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkInputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkIdentificacao))
                .addGap(18, 18, 18)
                .addGroup(painelPesquisaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPesquisaUsuarioLayout.createSequentialGroup()
                        .addComponent(checkEmail)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPesquisaUsuarioLayout.createSequentialGroup()
                        .addComponent(checkInputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(painelPesquisaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkPais)
                    .addComponent(checkInputPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelPesquisaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoLista)
                    .addComponent(botaoPesquisa))
                .addGap(18, 18, 18)
                .addComponent(scrollUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelPesquisaUsuarioLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {checkInputEmail, checkInputID, checkInputNome, checkInputPais});

        jTabbedPane1.addTab("Pesquisar usuário", painelPesquisaUsuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarUsuarioActionPerformed
        
        String nome = inputNome.getText();
        String id = AdministraUsuario.gerarId(persistenciaUsuario.getMapUsuarios());
        String email = inputEmail.getText();
        String senha = new String(inputSenha.getPassword());
        String pais = inputPais.getText();
        Papel papel = (Papel) caixaTipoUsuario.getSelectedItem();
        
        Usuario.StatusUsuario status = (Usuario.StatusUsuario) caixaStatusUsuario.getSelectedItem();
        
        if (papel instanceof Arbitro arbitro) {
            Integer experiencia = (Integer) caixaExperiencia.getSelectedItem();
            
            arbitro.setExperiencia(experiencia);   
        }
        
        Usuario usuarioCadastro = new Usuario(nome, id, email, pais, senha, status, papel);
        
        try {
            AdministraUsuario.criaUsuario(usuarioCadastro, persistenciaUsuario);
            JOptionPane.showMessageDialog(rootPane, "Usuário cadastrado com sucesso! Seu ID é: " + usuarioCadastro.getIdentificacao());
        }
        
        catch (CamposEmBrancoException | SenhaInsuficienteException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
             
    }//GEN-LAST:event_botaoSalvarUsuarioActionPerformed

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void botaoListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaActionPerformed
        List<Usuario> listaUsuario = AdministraUsuario.listaUsuario(persistenciaUsuario);
        preencheTabela(listaUsuario);
    }//GEN-LAST:event_botaoListaActionPerformed

    private void botaoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisaActionPerformed
        String nome = checkInputNome.getText();
        String email = checkInputEmail.getText();
        Papel papel = (Papel) caixaCheckFuncao.getSelectedItem();
        String pais = checkInputPais.getText();
        String id = checkInputID.getText();
        
        List<Usuario> resultadoPesquisa = AdministraUsuario.pesquisaUsuario(nome, id, email, pais, papel, persistenciaUsuario);
        
        preencheTabela(resultadoPesquisa);   
    }//GEN-LAST:event_botaoPesquisaActionPerformed

    private void checkPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPaisActionPerformed
        if (checkPais.isSelected() == false) {
            checkInputPais.setText("");
            checkInputPais.setEnabled(false);
        }
        else checkInputPais.setEnabled(true);
    }//GEN-LAST:event_checkPaisActionPerformed

    private void checkEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEmailActionPerformed
        if (checkEmail.isSelected() == false) {
            checkInputEmail.setText("");
            checkInputEmail.setEnabled(false);
        }
        else checkInputEmail.setEnabled(true);
    }//GEN-LAST:event_checkEmailActionPerformed

    private void checkIdentificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkIdentificacaoActionPerformed
        if (checkIdentificacao.isSelected() == false) {
            checkInputID.setText("");
            checkInputID.setEnabled(false);
        }
        else checkInputID.setEnabled(true);
    }//GEN-LAST:event_checkIdentificacaoActionPerformed

    private void checkFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFuncaoActionPerformed
        if (checkFuncao.isSelected() == false) {
            caixaCheckFuncao.setSelectedIndex(0);
            caixaCheckFuncao.setEnabled(false);
        }
        else caixaCheckFuncao.setEnabled(true);
    }//GEN-LAST:event_checkFuncaoActionPerformed

    private void checkInputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInputNomeActionPerformed
        // T
    }//GEN-LAST:event_checkInputNomeActionPerformed

    private void checkNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNomeActionPerformed
        if (checkNome.isSelected() == false) {
            checkInputNome.setText("");
            checkInputNome.setEnabled(false);
        }
        else checkInputNome.setEnabled(true);
    }//GEN-LAST:event_checkNomeActionPerformed

    private void caixaTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaTipoUsuarioActionPerformed
        Papel papel = (Papel) caixaTipoUsuario.getSelectedItem();
        
        if (papel instanceof Arbitro) {
            caixaExperiencia.setVisible(true);
            textoExperiencia.setVisible(true);
        }
        
        else {
            caixaExperiencia.setVisible(false);
            textoExperiencia.setVisible(false);
        }
    }//GEN-LAST:event_caixaTipoUsuarioActionPerformed

    private void caixaStatusUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaStatusUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaStatusUsuarioActionPerformed

    private void scrollUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollUsuariosMouseClicked

    }//GEN-LAST:event_scrollUsuariosMouseClicked

    private void tabelaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaUsuariosMouseClicked
        if (evt.getClickCount() == 1) {
            int linhaSelecionada = tabelaUsuarios.getSelectedRow();
            
            if (linhaSelecionada != -1) {
                String id = tabelaUsuarios.getValueAt(linhaSelecionada, 1).toString();
                
                SwingUtilities.invokeLater(() -> {
                    TelaUsuario janelaUsuario = new TelaUsuario(id, persistenciaUsuario);
                    janelaUsuario.setVisible(true);
                    janelaUsuario.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                });    
            }    
        }
    }//GEN-LAST:event_tabelaUsuariosMouseClicked

    private void caixaExperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaExperienciaActionPerformed
        
    }//GEN-LAST:event_caixaExperienciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new GestaoUsuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoLista;
    private javax.swing.JButton botaoPesquisa;
    private javax.swing.JButton botaoSalvarUsuario;
    private javax.swing.JComboBox<Papel> caixaCheckFuncao;
    private javax.swing.JComboBox<Integer> caixaExperiencia;
    private javax.swing.JComboBox<Usuario.StatusUsuario> caixaStatusUsuario;
    private javax.swing.JComboBox<Papel> caixaTipoUsuario;
    private javax.swing.JCheckBox checkEmail;
    private javax.swing.JCheckBox checkFuncao;
    private javax.swing.JCheckBox checkIdentificacao;
    private javax.swing.JTextField checkInputEmail;
    private javax.swing.JTextField checkInputID;
    private javax.swing.JTextField checkInputNome;
    private javax.swing.JTextField checkInputPais;
    private javax.swing.JCheckBox checkNome;
    private javax.swing.JCheckBox checkPais;
    private javax.swing.ButtonGroup grupoStatusUsuario;
    private javax.swing.ButtonGroup grupoTipoUsuario;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputPais;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel painelCadastraUsuario;
    private javax.swing.JPanel painelPesquisaUsuario;
    private javax.swing.JScrollPane scrollUsuarios;
    private javax.swing.JTable tabelaUsuarios;
    private javax.swing.JLabel textoEmail;
    private javax.swing.JLabel textoExperiencia;
    private javax.swing.JLabel textoNome;
    private javax.swing.JLabel textoPais;
    private javax.swing.JLabel textoSenha;
    private javax.swing.JLabel textoStatus;
    private javax.swing.JLabel textoTipoUsuario;
    // End of variables declaration//GEN-END:variables
}
