/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.administracao.telas;

import java.util.function.Supplier;
import java.util.stream.Stream;
import org.example.jogadorselecao.telas.*;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import org.example.administracao.*;
import org.example.partidas.telas.*;
import org.example.estadioArbitragem.*;
import org.example.ingressos.*;
import org.example.jogadorselecao.persistencia.IOJogador;
import org.example.jogadorselecao.persistencia.IOSelecao;


/**
 *
 * @author arkham
 */

public class TelaInicial extends javax.swing.JFrame {
    
    UsuarioLogado sessao;
    PersistenciaUsuario persistenciaUsuario; // carrega apenas se a permissao de administrador for aferida
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicial.class.getName());

    /**
     * Creates new form TelaInicial
     * @param sessao - o usuario que esta atualmente logado
     */
    public TelaInicial(UsuarioLogado sessao) {
        this.sessao = sessao;
        
        initComponents();
        desabilitaMenu();
        
        Supplier<Stream<? extends Permissao>> supplierPermissoes = () -> sessao.getUsuario().getPapel().getPermissoes().stream();
        
        if (supplierPermissoes.get().anyMatch(u -> u instanceof AdministraUsuario)) {
            persistenciaUsuario = new PersistenciaUsuario();
            menuAdministracao.setEnabled(true);
        }
        
        if (supplierPermissoes.get().anyMatch(u -> u instanceof IOJogador) && supplierPermissoes.get().anyMatch(u -> u instanceof IOSelecao)) {
            menuSelecoesJogadores.setEnabled(true);
        }
        
   
    }
    
    private void desabilitaMenu() { // o padrao eh que todos os menus estejam desabilitados, para que, com as permissoes do usuarios, sejam habilitados pouco a pouco
        menuAdministracao.setEnabled(false);
        menuEstadioArbitragem.setEnabled(false);
        menuPartidas.setEnabled(false);
        menuSelecoesJogadores.setEnabled(false);
        menuPublicoIngressos.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministracao = new javax.swing.JMenu();
        gerenciaUsuarios = new javax.swing.JMenuItem();
        relatorios = new javax.swing.JMenuItem();
        menuSelecoesJogadores = new javax.swing.JMenu();
        cadastraJogador = new javax.swing.JMenuItem();
        cadastraSelecao = new javax.swing.JMenuItem();
        consultaSelecaoJogador = new javax.swing.JMenuItem();
        menuPartidas = new javax.swing.JMenu();
        gerenciaPartidas = new javax.swing.JMenuItem();
        menuEstadioArbitragem = new javax.swing.JMenu();
        cadastraEstadio = new javax.swing.JMenuItem();
        cadastraArbitro = new javax.swing.JMenuItem();
        designaArbitro = new javax.swing.JMenuItem();
        menuPublicoIngressos = new javax.swing.JMenu();
        compraIngresso = new javax.swing.JMenuItem();
        controlePublico = new javax.swing.JMenuItem();
        relatorioFinanceiro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuAdministracao.setText("Administração");

        gerenciaUsuarios.setText("Gerenciar usuários...");
        gerenciaUsuarios.addActionListener(this::gerenciaUsuariosActionPerformed);
        menuAdministracao.add(gerenciaUsuarios);

        relatorios.setText("Relatórios...");
        relatorios.addActionListener(this::relatoriosActionPerformed);
        menuAdministracao.add(relatorios);

        jMenuBar1.add(menuAdministracao);

        menuSelecoesJogadores.setText("Seleções/Jogadores");

        cadastraJogador.setText("Cadastrar jogador...");
        cadastraJogador.addActionListener(this::cadastraJogadorActionPerformed);
        menuSelecoesJogadores.add(cadastraJogador);

        cadastraSelecao.setText("Cadastrar seleção...");
        cadastraSelecao.addActionListener(this::cadastraSelecaoActionPerformed);
        menuSelecoesJogadores.add(cadastraSelecao);

        consultaSelecaoJogador.setText("Consultar seleção/jogador...");
        consultaSelecaoJogador.addActionListener(this::consultaSelecaoJogadorActionPerformed);
        menuSelecoesJogadores.add(consultaSelecaoJogador);

        jMenuBar1.add(menuSelecoesJogadores);

        menuPartidas.setText("Partidas");

        gerenciaPartidas.setText("Gerenciar partidas...");
        gerenciaPartidas.addActionListener(this::gerenciaPartidasActionPerformed);
        menuPartidas.add(gerenciaPartidas);

        jMenuBar1.add(menuPartidas);

        menuEstadioArbitragem.setText("Estádios/Arbitragem");

        cadastraEstadio.setText("Cadastrar estádio...");
        cadastraEstadio.addActionListener(this::cadastraEstadioActionPerformed);
        menuEstadioArbitragem.add(cadastraEstadio);

        cadastraArbitro.setText("Cadastrar árbitro...");
        cadastraArbitro.addActionListener(this::cadastraArbitroActionPerformed);
        menuEstadioArbitragem.add(cadastraArbitro);

        designaArbitro.setText("Designar árbitro...");
        designaArbitro.addActionListener(this::designaArbitroActionPerformed);
        menuEstadioArbitragem.add(designaArbitro);

        jMenuBar1.add(menuEstadioArbitragem);

        menuPublicoIngressos.setText("Públicos/Ingressos");

        compraIngresso.setText("Comprar ingresso...");
        compraIngresso.addActionListener(this::compraIngressoActionPerformed);
        menuPublicoIngressos.add(compraIngresso);

        controlePublico.setText("Controle de público...");
        controlePublico.addActionListener(this::controlePublicoActionPerformed);
        menuPublicoIngressos.add(controlePublico);

        relatorioFinanceiro.setText("Relatórios financeiros...");
        relatorioFinanceiro.addActionListener(this::relatorioFinanceiroActionPerformed);
        menuPublicoIngressos.add(relatorioFinanceiro);

        jMenuBar1.add(menuPublicoIngressos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1056, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerenciaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciaUsuariosActionPerformed
        SwingUtilities.invokeLater(() -> {
            GestaoUsuarios janelaGestaoUsuarios = new GestaoUsuarios(sessao, persistenciaUsuario);
            janelaGestaoUsuarios.setVisible(true);
            janelaGestaoUsuarios.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        });
    }//GEN-LAST:event_gerenciaUsuariosActionPerformed

    private void relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatoriosActionPerformed
        SwingUtilities.invokeLater(() -> {
            Relatorios janelaRelatorios = new Relatorios();
            janelaRelatorios.setVisible(true);
            janelaRelatorios.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        });
    }//GEN-LAST:event_relatoriosActionPerformed

    private void cadastraJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraJogadorActionPerformed
        CadastroJogador painelCadastroJogador = new CadastroJogador();
        JDialog dialogo = new JDialog(this, "Cadastro de Jogador", true);
        dialogo.getContentPane().add(painelCadastroJogador);
        dialogo.pack();
        dialogo.setResizable(false);
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }//GEN-LAST:event_cadastraJogadorActionPerformed

    private void cadastraSelecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraSelecaoActionPerformed
        CadastroSelecao painelCadastroSelecao = new CadastroSelecao();
        JDialog dialogo = new JDialog(this, "Cadastro de Seleção", true);
        dialogo.getContentPane().add(painelCadastroSelecao);
        dialogo.pack();
        dialogo.setResizable(false);
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }//GEN-LAST:event_cadastraSelecaoActionPerformed

    private void consultaSelecaoJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaSelecaoJogadorActionPerformed
        ConsultaSelecaoJogador painelConsultaSelecaoJogador = new ConsultaSelecaoJogador();
        JDialog dialogo = new JDialog(this, "Consulta de jogadores/seleções", true);
        dialogo.getContentPane().add(painelConsultaSelecaoJogador);
        dialogo.pack();
        dialogo.setResizable(false);
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
    }//GEN-LAST:event_consultaSelecaoJogadorActionPerformed

    private void gerenciaPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciaPartidasActionPerformed
        SwingUtilities.invokeLater(() -> {
            Partida janelaPartidas = new Partida();
            janelaPartidas.setVisible(true);
            janelaPartidas.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        });
    }//GEN-LAST:event_gerenciaPartidasActionPerformed

    private void cadastraEstadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraEstadioActionPerformed
        SwingUtilities.invokeLater(() -> {
            TelaCadastroEstadio janelaCadastroEstadio = new TelaCadastroEstadio();
            janelaCadastroEstadio.setVisible(true);
            janelaCadastroEstadio.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        });
    }//GEN-LAST:event_cadastraEstadioActionPerformed

    private void cadastraArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraArbitroActionPerformed
        SwingUtilities.invokeLater(() -> {
            TelaCadastroArbitro janelaCadastroArbitro = new TelaCadastroArbitro();
            janelaCadastroArbitro.setVisible(true);
            janelaCadastroArbitro.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        });
    }//GEN-LAST:event_cadastraArbitroActionPerformed

    private void designaArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designaArbitroActionPerformed
        SwingUtilities.invokeLater(() -> {
            TelaDesignacaoArbitro janelaDesignacaoArbitro = new TelaDesignacaoArbitro();
            janelaDesignacaoArbitro.setVisible(true);
            janelaDesignacaoArbitro.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        });
    }//GEN-LAST:event_designaArbitroActionPerformed

    private void compraIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraIngressoActionPerformed
        SwingUtilities.invokeLater(() -> {
            TelaIngressoGUI janelaIngresso = new TelaIngressoGUI();
            janelaIngresso.setVisible(true);
            janelaIngresso.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        });
    }//GEN-LAST:event_compraIngressoActionPerformed

    private void controlePublicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlePublicoActionPerformed
        SwingUtilities.invokeLater(() -> {
            TelaControlePublicoGUI janelaPublico = new TelaControlePublicoGUI();
            janelaPublico.setVisible(true);
            janelaPublico.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        });
    }//GEN-LAST:event_controlePublicoActionPerformed

    private void relatorioFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioFinanceiroActionPerformed
        SwingUtilities.invokeLater(() -> {
            TelaRelatorioFinanceiroGUI janelaRelatorioFinanceiro = new TelaRelatorioFinanceiroGUI();
            janelaRelatorioFinanceiro.setVisible(true);
            janelaRelatorioFinanceiro.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        });
    }//GEN-LAST:event_relatorioFinanceiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        //java.awt.EventQueue.invokeLater(() -> new TelaInicial().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastraArbitro;
    private javax.swing.JMenuItem cadastraEstadio;
    private javax.swing.JMenuItem cadastraJogador;
    private javax.swing.JMenuItem cadastraSelecao;
    private javax.swing.JMenuItem compraIngresso;
    private javax.swing.JMenuItem consultaSelecaoJogador;
    private javax.swing.JMenuItem controlePublico;
    private javax.swing.JMenuItem designaArbitro;
    private javax.swing.JMenuItem gerenciaPartidas;
    private javax.swing.JMenuItem gerenciaUsuarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAdministracao;
    private javax.swing.JMenu menuEstadioArbitragem;
    private javax.swing.JMenu menuPartidas;
    private javax.swing.JMenu menuPublicoIngressos;
    private javax.swing.JMenu menuSelecoesJogadores;
    private javax.swing.JMenuItem relatorioFinanceiro;
    private javax.swing.JMenuItem relatorios;
    // End of variables declaration//GEN-END:variables
}
