/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.jogadorselecao.telas;

import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.example.jogadorselecao.Jogador;
import org.example.jogadorselecao.Posicao;
import org.example.jogadorselecao.StatusJogador;
import org.example.jogadorselecao.persistencia.ElementoDuplicado;
import org.example.jogadorselecao.persistencia.IOJogador;

/**
 *
 * @author jp67a
 */
public class CadastroJogador extends javax.swing.JPanel {

    private boolean isEditing;
    private int indice;
    /**
     * Creates new form CadastroJogador
     */
    public CadastroJogador() {
        initComponents();
        
        //Adiciona posicoes
        comboBoxPosicao.addItem(Posicao.CENTROAVANTE);
        comboBoxPosicao.addItem(Posicao.GOLEIRO);
        comboBoxPosicao.addItem(Posicao.LATERAL);
        comboBoxPosicao.addItem(Posicao.PONTA);
        comboBoxPosicao.addItem(Posicao.RESERVA);
        comboBoxPosicao.addItem(Posicao.VOLANTE);
        comboBoxPosicao.addItem(Posicao.ZAGUEIRO);
        
        //Adiciona Status
        comboBoxStatus.addItem(StatusJogador.ATIVO);
        comboBoxStatus.addItem(StatusJogador.LESIONADO);
        comboBoxStatus.addItem(StatusJogador.SUSPENSO);        
    }
    public CadastroJogador(boolean isEditing, int index){
        initComponents();
        
        this.isEditing = true;
        this.indice = index;
        
        //Adiciona posicoes
        comboBoxPosicao.addItem(Posicao.CENTROAVANTE);
        comboBoxPosicao.addItem(Posicao.GOLEIRO);
        comboBoxPosicao.addItem(Posicao.LATERAL);
        comboBoxPosicao.addItem(Posicao.PONTA);
        comboBoxPosicao.addItem(Posicao.RESERVA);
        comboBoxPosicao.addItem(Posicao.VOLANTE);
        comboBoxPosicao.addItem(Posicao.ZAGUEIRO);
        
        //Adiciona Status
        comboBoxStatus.addItem(StatusJogador.ATIVO);
        comboBoxStatus.addItem(StatusJogador.LESIONADO);
        comboBoxStatus.addItem(StatusJogador.SUSPENSO);   
        
        try{
            Jogador aux = IOJogador.get(index);
            txtInputNome.setText(aux.getNome());
            comboBoxPosicao.setSelectedItem(aux.getPosicao());
            txtInputNumero.setText(Integer.toString(aux.getNumero()));
            comboBoxStatus.setSelectedItem(aux.getStatus());
            txtInputData.setText(aux.getDataNascimento());
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERRO!", JOptionPane.ERROR_MESSAGE);            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNome = new javax.swing.JLabel();
        labelPosicao = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        txtInputNumero = new javax.swing.JTextField();
        txtInputNome = new javax.swing.JTextField();
        labelData = new javax.swing.JLabel();
        txtInputData = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        comboBoxPosicao = new javax.swing.JComboBox<>();
        comboBoxStatus = new javax.swing.JComboBox<>();

        labelNome.setText("Nome:");

        labelPosicao.setText("Posição:");

        labelNumero.setText("Número:");

        labelStatus.setText("Status:");

        labelData.setText("Data de Nascimento (dd/mm/yyyy):");

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(this::botaoSalvarActionPerformed);

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(this::botaoCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPosicao)
                                    .addComponent(labelNumero)
                                    .addComponent(labelStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtInputNome, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(txtInputNumero)
                                    .addComponent(comboBoxPosicao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboBoxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInputData, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(txtInputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPosicao)
                    .addComponent(comboBoxPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumero)
                    .addComponent(txtInputNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStatus)
                    .addComponent(comboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelData)
                    .addComponent(txtInputData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar)
                    .addComponent(botaoCancelar))
                .addGap(0, 10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja prosseguir?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION){
            SwingUtilities.getWindowAncestor(this).dispose();
        }
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        // TODO add your handling code here:
    
        //Tratamento de inputs inválidos
        try{
            Jogador jogador = new Jogador(txtInputNome.getText(),
                    (Posicao)comboBoxPosicao.getSelectedItem(), Integer.parseInt(txtInputNumero.getText()),
                    (StatusJogador)comboBoxStatus.getSelectedItem(), txtInputData.getText());
            if(isEditing){
                IOJogador.insert(jogador, indice);
            }
            else{
                IOJogador.appendJogador(jogador);
            }
            JOptionPane.showMessageDialog(null, txtInputNome.getText() + " foi cadastrado com sucesso.");
            SwingUtilities.getWindowAncestor(this).dispose();
        }
        catch(IllegalArgumentException | ElementoDuplicado | IOException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JComboBox<Posicao> comboBoxPosicao;
    private javax.swing.JComboBox<StatusJogador> comboBoxStatus;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelPosicao;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JTextField txtInputData;
    private javax.swing.JTextField txtInputNome;
    private javax.swing.JTextField txtInputNumero;
    // End of variables declaration//GEN-END:variables
}
