/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.jogadorselecao.telas;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.awt.Window;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.example.jogadorselecao.Jogador;
import org.example.jogadorselecao.Selecao;

/**
 *
 * @author jp67a
 */
public class ConsultaSelecaoJogador extends javax.swing.JPanel {

    /**
     * Creates new form ConsultaSelecaoJogador
     */
    public ConsultaSelecaoJogador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelOpcao = new javax.swing.JLabel();
        labelGrupo = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        labelPosicao = new javax.swing.JLabel();
        botaoConsultar = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        jRadioButtonSelecao = new javax.swing.JRadioButton();
        jRadioButtonJogador = new javax.swing.JRadioButton();
        comboBoxStatus = new javax.swing.JComboBox<>();
        comboBoxPosicao = new javax.swing.JComboBox<>();
        txtInputGrupo = new javax.swing.JTextField();
        botaoVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultaTable = new javax.swing.JTable();

        labelOpcao.setText("Selecione uma opção:");

        labelGrupo.setText("Grupo:");

        labelStatus.setText("Status:");

        labelPosicao.setText("Posição:");

        botaoConsultar.setText("Consultar");
        botaoConsultar.addActionListener(this::botaoConsultarActionPerformed);

        botaoEditar.setText("Editar");

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(this::botaoExcluirActionPerformed);

        buttonGroup1.add(jRadioButtonSelecao);
        jRadioButtonSelecao.setText("Seleção");
        jRadioButtonSelecao.addActionListener(this::jRadioButtonSelecaoActionPerformed);

        buttonGroup1.add(jRadioButtonJogador);
        jRadioButtonJogador.setText("Jogador");
        jRadioButtonJogador.addActionListener(this::jRadioButtonJogadorActionPerformed);

        comboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "LESIONADO", "SUSPENSO" }));

        comboBoxPosicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GOLEIRO", "ZAGUEIRO", "LATERAL", "VOLANTE", "PONTA", "CENTROAVANTE", "RESERVA" }));

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(this::botaoVoltarActionPerformed);

        jScrollPane1.setViewportView(consultaTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelOpcao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonSelecao)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonJogador)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelGrupo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInputGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botaoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelPosicao)
                                .addGap(8, 8, 8)
                                .addComponent(comboBoxPosicao, 0, 158, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOpcao)
                    .addComponent(jRadioButtonSelecao)
                    .addComponent(jRadioButtonJogador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGrupo)
                    .addComponent(labelStatus)
                    .addComponent(labelPosicao)
                    .addComponent(comboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInputGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEditar)
                    .addComponent(botaoConsultar)
                    .addComponent(botaoExcluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja prosseguir?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso.");
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void jRadioButtonSelecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSelecaoActionPerformed
        // TODO add your handling code here:
        txtInputGrupo.setEnabled(true);
        comboBoxPosicao.setEnabled(false);
        comboBoxStatus.setEnabled(false);
        
        //Altera dinamicamente a tabela
        File save = new File("src/main/resources/selecoes.jsonl"); //Configura arquivo de leitura
        String[] colunas = new String[] {"País", "Grupo", "Técnico"}; //Configura colunas

        consultaTable.clearSelection();
        consultaTable.setRowSorter(null);
        consultaTable.setModel(new DefaultTableModel(null, colunas)); //Configura modelo da Tabela (Quantidade de colunas e disposição destas)
        
        atualizaTabela(save, true); 
    }//GEN-LAST:event_jRadioButtonSelecaoActionPerformed

    private void jRadioButtonJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJogadorActionPerformed
        // TODO add your handling code here:
        txtInputGrupo.setEnabled(false);
        comboBoxPosicao.setEnabled(true);
        comboBoxStatus.setEnabled(true);
        
        //Altera dinamicamente a tabela
        File save = new File("src/main/resources/jogadores.jsonl"); //Configura arquivo de leitura
        String[] colunas = new String[] {"Nome", "Número", "Posição", "Status", "Seleção"}; //Configura colunas

        consultaTable.clearSelection();
        consultaTable.setRowSorter(null);
        consultaTable.setModel(new DefaultTableModel(null, colunas)); //Configura modelo da Tabela (Quantidade de colunas e disposição destas)
        atualizaTabela(save, false); 
    }//GEN-LAST:event_jRadioButtonJogadorActionPerformed
    
    private void atualizaTabela(File save, boolean tipo){//tipo = true - Tabela de Seleções; false - Tabela de Jogadores
        consultaTable.clearSelection(); //Desseleciona a linha atualmente selecionada
        DefaultTableModel modelo = (DefaultTableModel) consultaTable.getModel(); //Gera um modelo de tabela para manipulação da JTable
        modelo.setRowCount(0); //Zera o numero de linhas, efetivamente limpando a tabela
        Jogador jogador; //Molde para leitura de jogadores
        Selecao selecao; //Modde para leitura de selecoes
        
        ObjectMapper mapper = new ObjectMapper();// Instancia Mapeamento padrao da biblioteca Jackson
        String linha; //String auxiliar para leitura
        try(BufferedReader leitura = new BufferedReader(new FileReader(save))){   
            while((linha = leitura.readLine()) != null){
                if(!tipo){
                    jogador = mapper.readValue(linha, Jogador.class);
                    modelo.addRow(new Object[]{jogador.getNome(), jogador.getNumero(), jogador.getPosicao(),
                                               jogador.getStatus(), jogador.getNomeSelecao()});                   
                }
                else{
                    selecao = mapper.readValue(linha, Selecao.class);
                    modelo.addRow(new Object[]{selecao.getPais(), selecao.getGrupo(), selecao.getTecnico().getNome()});
                }

            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
        
        //Define seleção da linha inteira
        consultaTable.setRowSelectionAllowed(true);
        consultaTable.setColumnSelectionAllowed(false);
        
        //Centraliza os conteúdos das colunas
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < consultaTable.getColumnCount(); i++){
            consultaTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }    
    }
    
    private void botaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarActionPerformed
        // TODO add your handling code here:
        //Tratamento para caso de: Não foi selecionada uma categoria
        if(!(!txtInputGrupo.isEnabled() || !comboBoxStatus.isEnabled() || !comboBoxPosicao.isEnabled())){
            JOptionPane.showMessageDialog(null, "Selecione uma opção.", "Erro!", JOptionPane.OK_OPTION);
            return;
        }
        
        //Cria classe filtro 
        DefaultTableModel modelo = (DefaultTableModel) consultaTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
        
        if(!txtInputGrupo.isEnabled() && comboBoxPosicao.isEnabled() && comboBoxStatus.isEnabled()){
            
            //Cria filtro and customizado
            String status = comboBoxStatus.getSelectedItem().toString();
            String posicao = comboBoxPosicao.getSelectedItem().toString();
            RowFilter<DefaultTableModel, Object> filtro1 = RowFilter.regexFilter(status);
            RowFilter<DefaultTableModel, Object> filtro2 = RowFilter.regexFilter(posicao);
            List<RowFilter<DefaultTableModel, Object>> lista = new ArrayList<>();   //Caramba. Conversao dupla??!!
            lista.add(filtro1);
            lista.add(filtro2);
            RowFilter<DefaultTableModel, Object> filtros = RowFilter.andFilter(lista);
 
            sorter.setRowFilter(filtros); //Filtra tabela  
            consultaTable.setRowSorter(sorter);
        }
        else{
            try{
                String str = txtInputGrupo.getText().trim();
                int i = Integer.parseInt(str);
                if(i <= 0){
                    throw new IllegalArgumentException("Grupos devem ser números positivos.");
                }
                RowFilter<DefaultTableModel, Object> filtro = RowFilter.regexFilter(str);
                sorter.setRowFilter(filtro); //Filtra tabela
                consultaTable.setRowSorter(sorter);
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Grupo foi preenchido com um valor inválido.", "Erro!", JOptionPane.ERROR_MESSAGE);
                sorter.setRowFilter(null); //Filtra tabela
            }
            catch(IllegalArgumentException a){
                 JOptionPane.showMessageDialog(null, a.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);              
                 sorter.setRowFilter(null); //Filtra tabela
            }
        }
    }//GEN-LAST:event_botaoConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConsultar;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxPosicao;
    private javax.swing.JComboBox<String> comboBoxStatus;
    private javax.swing.JTable consultaTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonJogador;
    private javax.swing.JRadioButton jRadioButtonSelecao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelGrupo;
    private javax.swing.JLabel labelOpcao;
    private javax.swing.JLabel labelPosicao;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JTextField txtInputGrupo;
    // End of variables declaration//GEN-END:variables
}
