/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.estadioArbitragem.telas;

import java.util.List;
import javax.swing.JOptionPane;
import org.example.estadioArbitragem.Arbitro;
import org.example.estadioArbitragem.GerenciadorArbitroJSON;

/**
 *
 * @author helto
 */
public class TelaCadastroArbitro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroArbitro.class.getName());

    /**
     * Creates new form TelaCadastroArbitro
     */
    public TelaCadastroArbitro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroArb = new javax.swing.JPanel();
        jLabelNomeArb = new javax.swing.JLabel();
        jLabelNacionalidadeArb = new javax.swing.JLabel();
        jLabelExperienciaArb = new javax.swing.JLabel();
        txtNomeArb = new javax.swing.JTextField();
        txtNacionalidadeArb = new javax.swing.JTextField();
        txtExperienciaArb = new javax.swing.JTextField();
        jButtonSalvarCadArb = new javax.swing.JButton();
        jButtonFecharCadArb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCadastroArb.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Árbitro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabelNomeArb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNomeArb.setText("Nome completo:");

        jLabelNacionalidadeArb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNacionalidadeArb.setText("Nacionalidade:");

        jLabelExperienciaArb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelExperienciaArb.setText("Experiência:");

        txtNomeArb.addActionListener(this::txtNomeArbActionPerformed);

        txtExperienciaArb.addActionListener(this::txtExperienciaArbActionPerformed);

        jButtonSalvarCadArb.setText("Salvar");
        jButtonSalvarCadArb.addActionListener(this::jButtonSalvarCadArbActionPerformed);

        jButtonFecharCadArb.setText("Fechar");
        jButtonFecharCadArb.addActionListener(this::jButtonFecharCadArbActionPerformed);

        javax.swing.GroupLayout jPanelCadastroArbLayout = new javax.swing.GroupLayout(jPanelCadastroArb);
        jPanelCadastroArb.setLayout(jPanelCadastroArbLayout);
        jPanelCadastroArbLayout.setHorizontalGroup(
            jPanelCadastroArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroArbLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroArbLayout.createSequentialGroup()
                        .addComponent(jLabelNomeArb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeArb, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelExperienciaArb)
                    .addGroup(jPanelCadastroArbLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNacionalidadeArb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSalvarCadArb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelCadastroArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroArbLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanelCadastroArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtExperienciaArb, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNacionalidadeArb, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelCadastroArbLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonFecharCadArb, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanelCadastroArbLayout.setVerticalGroup(
            jPanelCadastroArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroArbLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeArb)
                    .addComponent(txtNomeArb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNacionalidadeArb)
                    .addComponent(txtNacionalidadeArb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelExperienciaArb, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExperienciaArb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanelCadastroArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarCadArb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFecharCadArb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroArb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroArb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeArbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeArbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeArbActionPerformed

    private void txtExperienciaArbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExperienciaArbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExperienciaArbActionPerformed

    private void jButtonSalvarCadArbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarCadArbActionPerformed
        if(txtNomeArb.getText().equals("") ||
                txtNacionalidadeArb.getText().equals("") ||
                txtExperienciaArb.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Verifique os campos em branco");
        
        } else {         
            try{
                String nome = txtNomeArb.getText();
                String nacionalidade = txtNacionalidadeArb.getText();
                int experiencia = Integer.parseInt(txtExperienciaArb.getText());

                Arbitro arbitro = new Arbitro(nome, nacionalidade, experiencia);

                GerenciadorArbitroJSON gajson = new GerenciadorArbitroJSON();
                
                List<Arbitro> listaParaSalvar = gajson.carregarArbitro();
                
                listaParaSalvar.add(arbitro);
                
                gajson.salvarArbitro(listaParaSalvar);
                
                JOptionPane.showMessageDialog(rootPane, "Árbitro cadastrado com sucesso!");
                
                txtNomeArb.setText("");
                txtNacionalidadeArb.setText("");
                txtExperienciaArb.setText("");
            } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "A experiência deve conter apenas números inteiros!");
            }
            
        }
    }//GEN-LAST:event_jButtonSalvarCadArbActionPerformed

    private void jButtonFecharCadArbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharCadArbActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharCadArbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroArbitro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFecharCadArb;
    private javax.swing.JButton jButtonSalvarCadArb;
    private javax.swing.JLabel jLabelExperienciaArb;
    private javax.swing.JLabel jLabelNacionalidadeArb;
    private javax.swing.JLabel jLabelNomeArb;
    private javax.swing.JPanel jPanelCadastroArb;
    private javax.swing.JTextField txtExperienciaArb;
    private javax.swing.JTextField txtNacionalidadeArb;
    private javax.swing.JTextField txtNomeArb;
    // End of variables declaration//GEN-END:variables

}